# Generated by Django 3.2.15 on 2022-08-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('desc', models.CharField(max_length=300)),
                ('sale', models.BooleanField(default=False)),
                ('sale_price', models.FloatField()),
            ],
        ),
    ]
