# Generated by Django 3.2.15 on 2022-08-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=15)),
                ('l_name', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('cat', models.CharField(max_length=5)),
                ('avatar', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
