# Generated by Django 3.2.15 on 2022-08-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsadmin', '0002_auto_20220826_0459'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='product',
            name='pic',
            field=models.CharField(default='pic.jpg', max_length=30),
        ),
    ]
